services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    network_mode: host

    command: tunnel --no-autoupdate run --token YOUR_TOKEN

    environment:
      TZ: Asia/Jakarta